application: blogger-aniket
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /Comments.py.*
  script: Comments.application

- url: /Blogs.py.*
  script: Blogs.application

- url: /UserLoggedIn.py.*
  script: UserLoggedIn.application
  
- url: /
  script: home.application

- url: /NewBlog.py.*
  script: NewBlog.application

- url: /InsertBlogToDataStore.py.*
  script: InsertBlogToDataStore.application
  
- url: /BlogFeed.py.*
  script: BlogFeed.application   
 
- url: /showCompleteBlog.py.*
  script: showCompleteBlog.application

- url: /searchByTags.py.*
  script: searchByTags.application

- url: /addComment.py.*
  script: addComment.application

- url: /addThumbsUp.py.*
  script: addThumbsUp.application
  
- url: /addThumbsDown.py.*
  script: addThumbsDown.application    
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest