application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: NewBlog.application

- url: /InsertBlogToDataStore.py.*
  script: InsertBlogToDataStore.application
  
- url: /BlogFeed.py.*
  script: BlogFeed.application
  
- url: /Blogs.py.*
  script: Blogs.application   
 
- url: /showCompleteBlog.py.*
  script: showCompleteBlog.application
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest