application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: NewBlog.application

- url: /InsertBlogToDataStore.py.*
  script: InsertBlogToDataStore.application  